# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "Yeonsang Shin"
subtitle: "신연상"
description: |
  Hello! I'm an undergraduate student in the Department of Electrical and Computer Engineering at <b>Seoul National University</b>. Currently, I'm serving as a research intern at the <b>Visual Computing Lab, KAIST</b>, advised by <b>Min H. Kim</b>. I've been fortunate to work with amazing Professors <i>Sungroh Yoon</i>, <i>Bohyung Han</i>, <i>Jongho Lee</i>, and <i>Kangwook Lee</i>.
  <br>
  My research in Computer Vision has progressed from structured visual representations (SVG, Layouts) to 3D Computer Vision. Currently, I'm exploring <b>Computational Imaging</b>, with a focus on Computer Graphics and camera systems. I'm particularly interested in leveraging generative AI across these domains.
  <br>
keywords:
- "Yeonsang Shin"
- "신연상"
- Computer Vision
- Diffusion Models
author: Yeonsang Shin
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yeonsangshin.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'projects/Vaker/**/*'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fengye

theme_config:
  year_align_center: false

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com-yeonsangshin:yeonsangshin/yeonsangshin.github.io.git
  branch: main

markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: false
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 2
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: ''
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: false
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # Set to 'right' to add permalink after heading
    permalinkSide: 'left'
    # The symbol used to make the permalink
    permalinkSymbol: '#'
    # Transform anchor to (1) lower case; (2) upper case
    case: 0
    # Replace space with a character
    separator: '-'
  plugins:
    - markdown-it-task-lists
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-abbr
  images:
    prepend_root: false
    post_asset: true

plugins:
  - name: '@renbaoshuo/markdown-it-katex'
    options:
      skipDelimitersCheck: true